manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ccai89
      url-base: https://github.com/ccai89
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: rp2040zero
      import: app/west.yml
  self:
    path: config
