manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nmunnich
      url-base: https://github.com/nmunnich/
  projects:
    - name: zmk
      remote: nmunnich
      revision: rp2040-zero
      import: app/west.yml
  self:
    path: config
