manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: glebsexy
      url-base: https://github.com/ccai89
  projects:
    - name: zmk
      remote: zmk-fifD4
      import: app/west.yml
  self:
    path: config
