manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: glebsexy
      url-base: https://github.com/glebsexy
    - name: ccai89
      url-base: https://github.com/ccai89
  projects:
    - name: zmk
      remote: ccai89
      import: app/west.yml
  self:
    path: config
